env:
  global:
  - secure: y/tKqZa/2Qg3qREDoIrgiwngKlhTNEwuym5Psh0Oy0S6ZJVJLwzf37AfFvTemgVuQu7oUfWSCgz+KNEK6jBzrCybZ1iKlY4OGxAxZ7D4jffWLz0dFtfxQN4YinqYp0MG4RY6mbCvpwDoXUhQGFV89rJwMkiOobfRuUTRMZH92NlQcF7gwmNhXfxfX9SM2hzcjFAg72bokLiRSV7Jqp5isQ+8JlvwDHHIY3JNbD+rVuDHGA9btWKK6SGZVHTX7brgsi+KyNQyqeBhfG5Cq1KctSTS0fWA5X6BCBf5Xre6fG53zJ/kTJgdQ+HqUw975zkFvbrukJLs0hTACdUN1q+ZeLSFLUxrox+PrklXQQSpcjty2O2aUFI/UmZ2IPcHvDp3QRsomLVaXl03JaYr5sxHSkpsfEKuBtRKSY9Aq+g18ET/8MfbI8K0tg8WRvEcXSg3knGppNPjpJEX+wDo0TUxJMDLJW/vh3MWYF3uV4Oo3kxA2NUdrUgZsqOxzX8KLpA/Oe7zSWn2Plg5ST7XJstX7S9ehUx1OLYH6iv2F/zSAlrTSMjB8nZeng7Xo825dOG8mhMSCzMwM2EYGd96Tr64BX04w923vttFyPdYq3xFT+JX933eLnelnNXTuhSsoBiYHN0mb9NcQYnItYZCOkNT1Q+La2IPfEb5YUciwbToqKI=
  - secure: qHw61fMpP62x5bHYv6Srk6/yn+uXdCZ5yIbTcGvYaPzv7JbcOosCE4CUsBZFomscKdUSrhJT4L/cBMrKTQzherOTeg93sU24Baxdgjq1iUDaEyMKPq8oTqpESJENgAd4WNTQ8tDZjuHkkvDHhL4qRFnSo4IdIyyTAeun9qNaumT/1RuLJ2X2/QB88qj6VPjO2hN2ojteI9vIT1En+rCL6nT4N9NYE/ZKLtcJH26X3tk3q3+WwYS/klysUI98lzGCj/W/WCszpgAlb+cFxHewjJNXzd8svQfy8OyawzD3QPzgRRSYBdpx/4jdZSSoHYzySTiZGFn9gM7wLxit8J4mcpK/8n1piiTnafufUttqRbZrcK649je9PG0uCBlX1kg3z0Hv8SgxBMV2dc3mkgfmIrYPSKCwC8nf9LWdK+xo1MiA7EnHWDNTVdZMJ11BJlfgET9FKNQQEvoXsqtozcmRxAlbxcw7rOpZCEKkilhmSQ/33Iz55PIQ0DVPutk2jlFf3CB0KwQ0rZsCvVYz8Ju5rLiknj7SswCHPbCVYu3ujuYUWWcOAKH0GPO3d85634APABjkdBcdRW6VNSyatvCmJc7zaFRAVQp7WR8bJbygcx4OOeyxxlK14P6dl2IEun5uYK8UbJMnjAkpWfeomiXMehL2MtUcu/96Fhz1PrQJuBg=

sudo: required

python:
  - "2.7"

# Clean and don't fail
install:
  - sudo pip install pygments
  - wget -O /tmp/hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.29/hugo_0.29_Linux-64bit.deb
  - sudo dpkg -i /tmp/hugo.deb
  - sudo apt install curl -y
  - chmod +x deploy.sh
  - chmod +x file_sizes.sh
  - rm -rf public || exit 0
  - npm install html-minifier -g

# Build the website
script:
  - pygmentize -V
  - git submodule update --init --recursive
  - hugo -v
  - sh file_sizes.sh
  - cd public
  - html-minifier --help
  
deploy:
  # deploy master to production
  - provider: script
    skip_cleanup: true
    script: sh deploy.sh
    on:
      branch: master
