sudo: required

python:
  - "2.7"

# Clean and don't fail
install:
  - sudo pip install pygments
  - wget -O /tmp/hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.40.3/hugo_0.40.3_Linux-64bit.deb
  - sudo dpkg -i /tmp/hugo.deb
  - sudo apt install curl -y
  - chmod +x deploy.sh
  - chmod +x file_sizes.sh
  - rm -rf public || exit 0
  - npm install html-minifier -g
  - sudo apt install -y lftp

# Build the website
script:
  - pygmentize -V
  - git submodule update --init --recursive
  - hugo -v
  - sh file_sizes.sh
  
deploy:
  # deploy master to production
  - provider: script
    skip_cleanup: true
    script: sh deploy.sh
    on:
      branch: master
