version: 1.0.{build}
image: Ubuntu
init:
- sh: sudo apt-get -y update
environment:
  FTP_USER:
    secure: VDlRdMrQ7xsTQfrkNt321g==
  FTP_PASSWORD:
    secure: b9qVmotjL8TdprxxIoFltA==
  FTP_HOST:
    secure: hA54lFXhy5GYDHxb4pJSCVzndZ+0wWk8JENLw1YKe5g=
  HUGO_VERSION: 0.91.0
install:
- sh: >-
    sudo apt-get install python3-pip

    sudo pip3 install pygments

    wget -O /tmp/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.deb

    sudo dpkg -i /tmp/hugo.deb

    sudo apt-get install curl -y

    pwd

    ls -all
    
    chmod +x file_sizes.sh

    chmod +x minify.sh

    chmod +x deploy.sh

    rm -rf public || exit 0

    npm install html-minifier -g
build_script:
- sh: >-
    pygmentize -V

    git submodule update --init --recursive

    hugo -v
test_script:
- sh: >-
    sh file_sizes.sh
    
    sh minify.sh
deploy_script:
- sh: sh deploy.sh
